version: '3'

services:
  consul:
      image: consul:1.4.0
      ports:
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
  redis:
      image: redis:5.0.1
      ports:
        - "6379:6379"
  vault:
      image: vault:0.11.5
      ports:
        - "8200:8200"
      cap_add:
        - IPC_LOCK
  mysql:
      image: mysql:5.6.40
      ports:
        - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: 123456
         MYSQL_DATABASE: spring_cloud